### PR TITLE
Fix for when the key IP has been incorrectly set to be that of a proxy

### PR DESCRIPTION
**Pull request by andrewhancox**

### CODE REVIEW

**Comment by dmitriim** [comment]
@andrewhancox looks like you have a lot of fun using this plugin :+1:  Could you please provide a bit more background on this issue. I'm not really sure that I can understand what's happening in the code.

**Comment by dmitriim** [comment]
Hi @andrewhancox 
Hope you are well. Any plans to continue working on this pull request?

**Comment by andrewhancox** [comment]
To be honest, I've now disabled this security feature as I had a steady drip of users who it didn't quite work for. There were a couple of cases where, for absolutely no reason I could see (no proxy/nat/etc. between the user and either of the systems) the connections came from different IPs - I think it MAY have been users going out through a load balanced connection but won't ever be able to find out.

**Comment by dmitriim** [comment]
@andrewhancox not a problem. I'll close this pull request then.

**Pull request closed without merging**
