### PR TITLE
Display locking profile fields

### PR DESCRIPTION
**Pull request by miguelurtado**
Display locking / mapping of profile fields

### CODE REVIEW

**Comment by dmitriim** [comment]
hey @miguelurtado !
Would be good if you can raise the issue first and describe the problem you are trying to fix with this patch. Others will be able to search and see that it's fixed. 

Cheers!

**Comment by miguelurtado** [comment]
Hello, sorry for delay reply.

This add control for users edit fields in profile.

image

Thanks

**Comment by dmitriim** [comment]
Thanks @miguelurtado !
However, what would you expect from this setting? I think your patch just displays it, but doesn't actually do anything with the configured fields. Would you like to improve it and actually utilise those settings in the user creation logic?

**Comment by miguelurtado** [comment]
Hello @dmitriim this path work in native Moodle settings. For example, if the First Name field is blocked. When user access the edit profile this field is not editable.

Thanks

**Comment by dmitriim** [comment]
Ah ok. Looks good to me. Thanks for contribution. Merging it in.

**Pull request merged**
