### PR TITLE
settings.php for 3.2 to 3.4 Moodle version

### PR DESCRIPTION
**Pull request by hoz1982**

### CODE REVIEW

**Comment by dmitriim** [comment]
Hey @hoz1982 !
Thanks for your contribution. Looks like travis is not happy. Could you please have a look and fix it before we can do review of your changes. Looks like it complains about some missing lang string.

**Comment by hoz1982** [comment]
Hi @dmitriim! ok maybe it was something on the $option array...
I'm opening a new pull request with the correct file.

**Comment by dmitriim** [comment]
Hi @hoz1982 !
Looks like you need to fix coding style in your code to make travis happy. 
Please see https://docs.moodle.org/dev/Coding_style for more info.

**Comment by dmitriim** [comment]
Also some unit tests are broken as well.

**Comment by andrewhancox** [comment]
I hadn't realised some else had already done this. I've got a working branch at https://github.com/andrewhancox/moodle-auth_userkey/tree/master_33

**Comment by dmitriim** [comment]
Hi @hoz1982 

This functionality has just landed to MOODLE_33PLUS branch.  Thank you for your work on this plugin.

Cheers,
Dmitrii

**Pull request closed without merging**
